version: '3.8'

services:
  api:
    build: .
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - PORT=8090
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped