version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: edor-api-prod
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - PORT=8090
      - BASE_URL=http://localhost:8090
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - edor-network
    # Limites de ressources pour la production
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  edor-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  logs:
    driver: local
