version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - PORT=8090
      - BASE_URL=http://localhost:8090
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
