version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: edor-api-dev
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=development
      - PORT=8090
      - BASE_URL=http://localhost:8090
    volumes:
      # Montage du code source pour le développement
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - edor-network

networks:
  edor-network:
    driver: bridge
