// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe4G2HVesjhxNNcBiE3YgpDUULJjFdUew',
    appId: '1:205344853554:web:bcebc6da88dce4374eb62b',
    messagingSenderId: '205344853554',
    projectId: 'edor-mobile',
    authDomain: 'edor-mobile.firebaseapp.com',
    storageBucket: 'edor-mobile.firebasestorage.app',
    measurementId: 'G-HFDJCY3PB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fRVrhyEs0ugXFH2o0vWRvca5MFCO6Gs',
    appId: '1:205344853554:android:6590c1d31178a0fd4eb62b',
    messagingSenderId: '205344853554',
    projectId: 'edor-mobile',
    storageBucket: 'edor-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6q0a_Y3ayWRYTy9K16L00l5z6QBS_bk4',
    appId: '1:205344853554:ios:401507cca09027f74eb62b',
    messagingSenderId: '205344853554',
    projectId: 'edor-mobile',
    storageBucket: 'edor-mobile.firebasestorage.app',
    iosClientId: '205344853554-l8gfu0tknq27gc5oi9d668a0m51imm8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.edor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6q0a_Y3ayWRYTy9K16L00l5z6QBS_bk4',
    appId: '1:205344853554:ios:401507cca09027f74eb62b',
    messagingSenderId: '205344853554',
    projectId: 'edor-mobile',
    storageBucket: 'edor-mobile.firebasestorage.app',
    iosClientId: '205344853554-l8gfu0tknq27gc5oi9d668a0m51imm8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.edor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe4G2HVesjhxNNcBiE3YgpDUULJjFdUew',
    appId: '1:205344853554:web:9057362a070ab1d84eb62b',
    messagingSenderId: '205344853554',
    projectId: 'edor-mobile',
    authDomain: 'edor-mobile.firebaseapp.com',
    storageBucket: 'edor-mobile.firebasestorage.app',
    measurementId: 'G-RBRSQCPC04',
  );

}